create table if not exists public.user_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  user_email text,
  name text,
  feedback_text text not null,
  source_page text,
  created_at timestamptz not null default now(),
  constraint user_feedback_feedback_text_not_empty check (char_length(trim(feedback_text)) > 0)
);

create index if not exists user_feedback_created_at_idx
  on public.user_feedback (created_at desc);

create index if not exists user_feedback_user_id_idx
  on public.user_feedback (user_id);

alter table public.user_feedback enable row level security;

drop policy if exists "Anyone can submit feedback" on public.user_feedback;
create policy "Anyone can submit feedback"
  on public.user_feedback
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Users can read their own feedback" on public.user_feedback;
create policy "Users can read their own feedback"
  on public.user_feedback
  for select
  to authenticated
  using (auth.uid() = user_id);
